name: Project Activity
author: Andy
description: Generates a summary of project activity, showing issues that have moved, been added or commented.
inputs:
    token:
        description: "Github Token"
        required: true
    project-numbers:
        description: "Project Numbers (comma-separated list, or, all)"
        required: true
    days:
        description: "Days back, from run date, of project activity to summarise"
        required: true
runs:
    using: "node12"
    main: "index.js"
branding:
    icon: 'activity'
    color: 'blue'
